version: 2

workflows:
  version: 2
  test:
    jobs:
      - test37
      - test38
      - test39

jobs:
  test37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: pip install --user tox
      - run: tox -e py37

  test38:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: pip install --user tox
      - run: tox -e py38

  test39:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run: pip install --user tox
      - run: tox -e py39
