# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: chronoforge tool

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-pyjq:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
    steps:
    # Checkout repo and setup python
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Set up Python ${{ matrix.python-version }}
      id: setup-python
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38
      with:
        python-version: "${{ matrix.python-version }}"
    - run: sudo apt-get install python3-pip libjq-dev libonig-dev automake autoconf libtool
    - run: pip3 install pipenv
    - run: pipenv install --dev
    - run: pipenv run python3 setup.py build
    - run: ls build/
  build-arm:
    runs-on: arm64-beta-public
    strategy:
      matrix:
        python-version: [3.11, 3.12]
    steps:
    # Checkout repo and setup python
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Set up Python ${{ matrix.python-version }}
      id: setup-python
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38
      with:
        python-version: "${{ matrix.python-version }}"
    - run: sudo apt-get install python3-pip libjq-dev libonig-dev automake autoconf libtool
    - run: pip3 install pipenv
    - run: pipenv install --dev
    - run: pipenv run python3 setup.py build
    - run: ls build/
